"""add_gitlab_connector_and_trpc_bridge_indexes

Revision ID: 8a0998e7f55f
Revises: cf4371bc740e
Create Date: 2026-04-30 15:38:47.448788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0998e7f55f'
down_revision: Union[str, None] = 'cf4371bc740e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_integrations_type", "integrations", ["type"], unique=False)
    op.create_index("ix_integrations_enabled", "integrations", ["enabled"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_integrations_enabled", table_name="integrations")
    op.drop_index("ix_integrations_type", table_name="integrations")
    # ### end Alembic commands ###
